// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectFinal.Data;

#nullable disable

namespace ProiectFinal.Migrations
{
    [DbContext(typeof(ProiectFinalContext))]
    partial class ProiectFinalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProiectFinal.Models.Cal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AnulNasterii")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorID")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NumeCal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("InstructorID");

                    b.ToTable("Cal");
                });

            modelBuilder.Entity("ProiectFinal.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NumeCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("ProiectFinal.Models.CategorieCal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CalID")
                        .HasColumnType("int");

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CalID");

                    b.HasIndex("CategorieID");

                    b.ToTable("CategorieCal");
                });

            modelBuilder.Entity("ProiectFinal.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("ProiectFinal.Models.Cal", b =>
                {
                    b.HasOne("ProiectFinal.Models.Instructor", "Instructor")
                        .WithMany("Cai")
                        .HasForeignKey("InstructorID");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ProiectFinal.Models.CategorieCal", b =>
                {
                    b.HasOne("ProiectFinal.Models.Cal", "Cal")
                        .WithMany("CategoriiCai")
                        .HasForeignKey("CalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectFinal.Models.Categorie", "Categorie")
                        .WithMany("CategoriiCal")
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cal");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("ProiectFinal.Models.Cal", b =>
                {
                    b.Navigation("CategoriiCai");
                });

            modelBuilder.Entity("ProiectFinal.Models.Categorie", b =>
                {
                    b.Navigation("CategoriiCal");
                });

            modelBuilder.Entity("ProiectFinal.Models.Instructor", b =>
                {
                    b.Navigation("Cai");
                });
#pragma warning restore 612, 618
        }
    }
}
